### ISSUE TITLE
Cannot allocate memory: unknown in template creation

### ISSUE THREAD

**Issue by hananmoiseyev** [kvdi/kvdi#32]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: mkdir /sys/fs/cgroup/memory/docker/48f82b4914f55027cfb887db030760b9608d9992a263f16cdeb110eb4d564292: cannot allocate memory: unknown.

**Comment by tinyzimmer** [comment]
There is absolutely no information in this issue and the error is that from a docker daemon. Almost certainly a system issue. 

I you **actually** think it's related to kvdi, open an issue with more information and a better description.
