### ISSUE TITLE
Please make all URL and image references dyamically configurable

### ISSUE THREAD

**Issue by caduceus4** [kvdi/kvdi#33]
Some folks are forced to use private registries on a disconnected network. Two things I have found that do not appear configurable apart from editing code in place are:

1. after templating via helm, there is an image reference in: kvdi/templates/deployment.yaml:

image: ghcr.io/kubebuilder/kube-rbac=proxy:v0.5.0

I do not see a k8s way of changing that one to a private registry (currently resorting to a sed script during build (yuk)).  I could be wrong on there not being a way to change this via k8s.

2. On the kvdi GUI, you have an icon as a link to: https://cdn.quasar.dev/logo/svg/quasar-logo.svg That should either be included in the distribution or otherwise configurable.

There may be others. The first one tripped me up for a few hours ;-)

**Comment by tinyzimmer** [comment]
1 - should be easy to do. The rbac-proxy is something newish that came with the kubebuilder v3 migration. But you are right, the chart should expose values for pointing it at a private registry. I don't know of a k8s way to point that a private registry the way it is, it would depend on your container runtime. For instance in `containerd` you can configure it to auto redirect certain repos to a local one. 

2 - I never realized that logo was getting pulled from a CDN. I thought it was getting bundled into the distribution.  I desperately want to replace that logo regardless, but I'll at the very least see if I can find some way to fix the way it is now.
