### ISSUE TITLE
changing ui tab, leads to logging out

### ISSUE THREAD

**Issue by umberto10** [kvdi/kvdi#36]
Hi there,
I was using ubuntu template, then I changed tab to API, and starting from there all API request are code 403
![image](https://user-images.githubusercontent.com/43953088/110794817-6eb46500-8276-11eb-918f-253083c25f25.png)
and I cannot connect back to session:
![image](https://user-images.githubusercontent.com/43953088/110795014-a1f6f400-8276-11eb-8c56-a4afbb5e7de9.png)
I don't know where is the problem.
My config:
```
vdi:
  spec:
    appNamespace: k8s-kvdi
    app:
      serviceType: ClusterIP
      #corsEnabled: true
      resources:
        limits:
          cpu: "2000m"
          memory: "2G"
        requests:
          cpu: "1000m"
          memory: "1G"
    auth:
      tokenDuration: "8h"
      oidcAuth:
        preserveTokens: True
        #issuerURL: ""
        issuerURL: ""
        clientCredentialsSecret: ""
        #redirectURL: ""
        redirectURL: ""
        #scopes: [ "email", "profile", "groups" ]
        groupScope: kvdi-policy
        adminGroups: [ "admin-user" ]
        allowNonGroupedReadOnly: True

**Comment by umberto10** [comment]
I think it's due to oidc token expiration

**Comment by tinyzimmer** [comment]
If it was due to the OIDC expiration that makes sense and is the expected behavior. The UI could have a cleaner approach to this happening, but I'll defer that to the redesign I have in mind. I've got someone who might be willing to help with it as well.
